### ISSUE TITLE
Upgrade to 7.9.2

### ISSUE THREAD

**Issue by vincentfree** [reactiverse/elasticsearch-client#10]
Hi,

I just found out that there is a newer version through a low vulnerability in version `0.8.3-ec7.8.0`
https://snyk.io/vuln/SNYK-JAVA-ORGELASTICSEARCH-1021613

Although this is very minor the real reason for this request is to keep up with the releases 😄 

Thanks upfront!

**Comment by vincentfree** [comment]
Looking at the `build.gradle.kts` file I see that the release is imminent 👍🏽
Maybe the upgrade to vertx version `3.9.4` 😉

**Comment by jponge** [comment]
@vincentfree fancy a PR with upgrades?

**Comment by vincentfree** [comment]
Yes a update of the elastic version and vertx. It's no big problem at the moment but I got triggered by a cve to look if you've updated the library to the newest version. I saw you had the new elastic version in the build.gradle file but there has not been a release of that version.

**Comment by jponge** [comment]
0.8.4-ec7.10.1 has been released
