### ISSUE TITLE
How to setup and use your project?

### ISSUE THREAD

**Issue by imcvampire** [reactiverse/elasticsearch-client#2]
Hi, 

Can you share with me a complete guide to setup and use your code on a vertx project? Thank you!

**Comment by jponge** [comment]
Use it as a library, then you can connect like stated in the `README`.

**Comment by imcvampire** [comment]
@jponge How can I config Elasticsearch client like hosts, port, tls, ...

**Comment by jponge** [comment]
See https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-getting-started-initialization.html and how to pass configuration like in https://github.com/reactiverse/elasticsearch-client/blob/master/integration-tests/src/test/java/integration/RxJava2Tests.java
