### ISSUE TITLE
Upgrade to client version 7.5.1

### ISSUE THREAD

**Issue by vincentfree** [reactiverse/elasticsearch-client#3]
Hi Julien,

I'm using your client in one of my new projects, were are version 7.4.2 at the moment but the team managing Elastic is upgrading to 7.5.1 soon. Hope you could release a new version of this lib as well.

P.s. I want to say thank you for making this library! 😄

**Comment by jponge** [comment]
Thanks for the kind works @vincentfree 🙏

**Comment by jponge** [comment]
Trying a bump to 7.5.1, seems like there have been API changes that break the generation process.

**Comment by jponge** [comment]
Ooops, my mistake (forgot to clean generated files)

**Comment by jponge** [comment]
Next: publish a release

**Comment by jponge** [comment]
@vincentfree I have issues with Sonatype OSS, see https://issues.sonatype.org/browse/OSSRH-54448

You can checkout the source code yourself though.

Note that I will be unavailable for 1-2 weeks, so I may be slow to respond.

**Comment by jponge** [comment]
@vincentfree You can use `0.8.1ec7.5.1`, it's been released to Maven Central.

The problem with the earlier error is that Sonatype has issues with secure checksum files being rejected, so Gradle needs to be told not to generate these but stick to md5 and sha1 (which are broken).

**Comment by vincentfree** [comment]
Hi @jponge sorry for the late response, I'll upgrade to the new lib tomorrow and let you know how it works out. Do you know if elastic has any plans for a real reactive client or a possibility to have responses pushed like a reactive client? I couldn’t find a definitive answer online

**Comment by jponge** [comment]
I have no idea about that, you'd need to ping someone from Elastic. Perhaps @dadoonet can help?

**Comment by vincentfree** [comment]
I did find this open issue which is a async version of search containing a partial result instead of having to wait for a full result with a possible long duration. 
It's proposed for version `7.7.0` or `8.0.0`
https://github.com/elastic/elasticsearch/pull/49931

**Comment by dadoonet** [comment]
> I have no idea about that, you'd need to ping someone from Elastic. Perhaps @dadoonet can help?

I just asked @philkra who told me that we don't have any plan at the moment for this.

**Comment by philkra** [comment]
> I'm using your client in one of my new projects, were are version 7.4.2 at the moment but the team managing Elastic is upgrading to 7.5.1 soon.

You can use a `7.4.x` client with Elasticsearch `7.5.x`, the only implications are that the client doesn’t expose the new features that went into `7.5.0`. You should not face any difficulties.
