### ISSUE TITLE
Upgrade to client version 7.8.0

### ISSUE THREAD

**Issue by Urban82** [reactiverse/elasticsearch-client#7]
Hi @jponge,

it is possible to release a new version with the IndicesClient now enabled again and with the client version 7.8.0 that was released a month ago?

Thank you for your work!

PS: I tried it locally and it builds correctly, but I'm not sure about how you prefer to split the commits. If you want I can make a pull request with the changes I made.

**Comment by jponge** [comment]
Hi @Urban82 yes please open a single PR with the version changes and we'll move on from here 👍

**Comment by Urban82** [comment]
Done, it is PR #8

**Comment by jponge** [comment]
Released `0.8.3-ec7.8.0`, it should be available in Maven Central in the next hour or so.
